-- Migration Assessment App — Database Schema
-- Oracle Autonomous Database (ADB)
-- Run this against your ADB instance to create the required tables

-- VM Inventory (populated from RVTools export)
CREATE TABLE RVTOOLS_VINFO (
    VM_NAME           VARCHAR2(255),
    POWERSTATE        VARCHAR2(50),
    DNS_NAME          VARCHAR2(255),
    CLUSTER_NAME      VARCHAR2(255),
    PRIMARY_IP        VARCHAR2(50),
    APPLICATION       VARCHAR2(255),
    CPUS              NUMBER,
    MEMORY_MB         NUMBER,
    TOTAL_DISK_MIB    NUMBER,
    OS_CONFIG         VARCHAR2(500),
    MIGRATION_TARGET  VARCHAR2(50),
    MIGRATION_WAVE    NUMBER,
    DATACENTER        VARCHAR2(255),
    HOST_NAME         VARCHAR2(255),
    VM_CRITICALITY    VARCHAR2(50),
    VM_ENVIRONMENT    VARCHAR2(50)
);

-- Application Inventory (catalog of all applications)
CREATE TABLE APP_INVENTORY (
    APP_ID                  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    APP_NAME                VARCHAR2(255),
    VENDOR                  VARCHAR2(255),
    CATEGORY                VARCHAR2(100),
    ENVIRONMENT             VARCHAR2(50),
    CRITICALITY             VARCHAR2(50),
    MIGRATION_STRATEGY      VARCHAR2(100),
    TARGET_OCI_SERVICE      VARCHAR2(255),
    MIGRATION_WAVE          NUMBER,
    MIGRATION_COMPLEXITY    VARCHAR2(50),
    ESTIMATED_EFFORT_DAYS   NUMBER,
    MONTHLY_COST_CURRENT    NUMBER(12,2),
    MONTHLY_COST_OCI        NUMBER(12,2)
);

-- Migration Plan (per-application migration decisions)
CREATE TABLE APP_MIGRATION_PLAN (
    PLAN_ID           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    APPLICATION       VARCHAR2(255),
    VM_COUNT          NUMBER,
    TOTAL_CPUS        NUMBER,
    TOTAL_MEM_GB      NUMBER(10,2),
    TOTAL_DISK_TB     NUMBER(10,2),
    APP_CATEGORY      VARCHAR2(100),
    MIGRATION_TARGET  VARCHAR2(50),
    TARGET_SERVICE    VARCHAR2(255),
    MIGRATION_WAVE    NUMBER,
    COMPLEXITY        VARCHAR2(50),
    RISK_LEVEL        VARCHAR2(50),
    ESTIMATED_DAYS    NUMBER,
    STATUS            VARCHAR2(50) DEFAULT 'Planned',
    NOTES             VARCHAR2(4000)
);

-- Indexes for common queries
CREATE INDEX IDX_VINFO_CLUSTER ON RVTOOLS_VINFO(CLUSTER_NAME);
CREATE INDEX IDX_VINFO_APP ON RVTOOLS_VINFO(APPLICATION);
CREATE INDEX IDX_VINFO_TARGET ON RVTOOLS_VINFO(MIGRATION_TARGET);
CREATE INDEX IDX_PLAN_TARGET ON APP_MIGRATION_PLAN(MIGRATION_TARGET);
CREATE INDEX IDX_PLAN_WAVE ON APP_MIGRATION_PLAN(MIGRATION_WAVE);
CREATE INDEX IDX_INV_CATEGORY ON APP_INVENTORY(CATEGORY);
